---
- name: Retrieve docker container facts
  docker_container_info:
    name: "{{ item.name }}"
  register: is_item

- name: tasks list to do once
  shell: "{{ iter_shell }}"
  loop: "{{ item.task_todo_once }}"
  loop_control:
    loop_var: iter_shell
  when:
    - is_item.exists == false
    - item.task_todo_once is defined
...