---
- name: Create/remove filesystem directories
  file:
    path: "/export/{{ iter_create.dest }}"
    state: directory
    mode: "0755"
    recurse: yes

- name: Create mount points
  mount:
    path: "/export/{{ iter_create.dest }}"
    src: "{{ iter_create.src }}"
    opts: bind
    state: mounted
    fstype: none