---
- name: Install nfs server
  apt:
    name: nfs-kernel-server
    state: present

- name: Create export directory
  file:
    path: "/export"
    state: directory
    mode: "0755"

- name: Create nfs filesystem and mountpoint
  include: create_nfs.yaml
  loop: "{{ nfs }}"
  loop_control:
    loop_var: iter_create
  when: iter_create.state == "present"

- name: Remove nfs mountpoint and filesystem
  include: remove_nfs.yaml
  loop: "{{ nfs }}"
  loop_control:
    loop_var: iter
  when: iter.state == "absent"

- name: copy /etc/exports
  template:
    src: "exports.j2"
    dest: "/etc/exports"
    owner: "root"
    group: "root"

- name: Restart nfs service
  service:
    name: nfs-kernel-server
    state: restarted