---
- name: Set timezone to "{{ local_timezone }}"
  timezone:
    name: "{{ local_timezone }}"

- name: Update and upgrade nas
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  apt:
    name: "{{ packages_list }}"
...