---
- name: Set timezone to "{{ local_timezone }}"
  timezone:
    name: "{{ local_timezone }}"

- name: Update Debian based OS
  apt:
    autoclean: yes
    autoremove: yes
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install packages
  package:
    name: "{{ packages_list }}"
    state: present
...